'use client'

// The Venice verdict card — visible Venice IMAGE output, in the main flow.
// Venice renders the broadcast artwork; we overlay the crisp verdict text.

import { useEffect, useState } from 'react'
import { CF, alpha } from '../lib/theme'

export function VerdictCard({
  callId, side, marketTitle, agentHandle, pct,
}: {
  callId: string
  side: 'YES' | 'NO'
  marketTitle: string
  agentHandle: string
  pct: number
}) {
  const [dataUrl, setDataUrl] = useState<string | null>(null)
  const [state, setState] = useState<'idle' | 'loading' | 'error'>('idle')
  const sideColor = side === 'YES' ? CF.bull : CF.bear

  useEffect(() => {
    let alive = true
    fetch(`/api/verdict-card/${callId}`)
      .then((r) => r.json())
      .then((d) => { if (alive && d.cached && d.dataUrl) setDataUrl(d.dataUrl) })
      .catch(() => {})
    return () => { alive = false }
  }, [callId])

  async function generate() {
    setState('loading')
    try {
      const r = await fetch(`/api/verdict-card/${callId}`, { method: 'POST' })
      const d = await r.json()
      if (d.dataUrl) { setDataUrl(d.dataUrl); setState('idle') }
      else setState('error')
    } catch { setState('error') }
  }

  return (
    <section style={{ marginTop: 14 }}>
      <div className="mono" style={{ fontSize: 10.5, letterSpacing: 1.6, color: CF.ink3, marginBottom: 10, display: 'flex', alignItems: 'center', gap: 8 }}>
        <span style={{ width: 6, height: 6, borderRadius: '50%', background: CF.gold }} />
        VENICE VERDICT CARD
      </div>

      <div style={{
        position: 'relative', width: '100%', aspectRatio: '16 / 10',
        borderRadius: CF.radius.lg, overflow: 'hidden',
        border: `1px solid ${CF.line}`, background: CF.surface2, boxShadow: CF.shadow.card,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
      }}>
        {dataUrl ? (
          <>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={dataUrl} alt="Venice-generated verdict card" style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover' }} />
            {/* legibility scrim */}
            <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(180deg, rgba(3,7,12,0.25) 0%, rgba(3,7,12,0.55) 55%, rgba(3,7,12,0.85) 100%)' }} />
            {/* overlay verdict */}
            <div style={{ position: 'absolute', inset: 0, padding: '20px 24px', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                <span className="mono" style={{ fontSize: 10, letterSpacing: 1.4, color: '#F0E9D7', background: 'rgba(0,0,0,0.4)', padding: '4px 9px', borderRadius: 999 }}>
                  CROSSFIRE · WORLD CUP ’26
                </span>
                <span className="mono" style={{ fontSize: 9.5, letterSpacing: 1, color: CF.gold, background: 'rgba(0,0,0,0.45)', padding: '4px 9px', borderRadius: 999 }}>
                  ✦ generated by Venice
                </span>
              </div>
              <div>
                <div style={{ fontFamily: CF.display, fontSize: 'clamp(48px, 9vw, 92px)', fontWeight: 700, lineHeight: 0.9, letterSpacing: -2, color: sideColor, textShadow: '0 2px 24px rgba(0,0,0,0.6)' }}>
                  {side}
                </div>
                <div style={{ fontFamily: CF.body, fontSize: 15, fontWeight: 600, color: '#F0E9D7', marginTop: 8, maxWidth: '85%', textShadow: '0 1px 8px rgba(0,0,0,0.8)' }}>
                  {marketTitle}
                </div>
                <div className="mono" style={{ fontSize: 11.5, color: '#CFC9BB', marginTop: 6, textShadow: '0 1px 6px rgba(0,0,0,0.8)' }}>
                  AGENT {agentHandle} · {pct}% conviction
                </div>
              </div>
            </div>
          </>
        ) : state === 'loading' ? (
          <div style={{ textAlign: 'center', padding: 32 }}>
            <div className="cf-think" style={{ display: 'inline-flex', gap: 5, marginBottom: 12 }}>
              <span style={{ width: 7, height: 7, borderRadius: '50%', background: CF.gold }} />
              <span style={{ width: 7, height: 7, borderRadius: '50%', background: CF.gold }} />
              <span style={{ width: 7, height: 7, borderRadius: '50%', background: CF.gold }} />
            </div>
            <div className="mono" style={{ fontSize: 12, color: CF.ink2 }}>Venice is painting the verdict…</div>
            <div className="mono" style={{ fontSize: 10.5, color: CF.ink4, marginTop: 4 }}>image endpoint · venice-sd35 · ~15s</div>
          </div>
        ) : (
          <div style={{ textAlign: 'center', padding: 28 }}>
            <div style={{ fontFamily: CF.body, fontSize: 14, color: CF.ink2, marginBottom: 14, maxWidth: 360 }}>
              {state === 'error' ? 'Couldn’t reach Venice — try again.' : 'Render this call as a broadcast verdict card with Venice’s image model.'}
            </div>
            <button onClick={generate} style={{
              padding: '11px 20px', borderRadius: CF.radius.md, border: 'none', cursor: 'pointer',
              background: `linear-gradient(180deg, ${CF.gold}, ${alpha(CF.gold, 70)})`,
              color: '#1a1305', fontFamily: CF.body, fontWeight: 700, fontSize: 13, letterSpacing: 0.3,
            }}>
              ✦ Generate verdict card · Venice
            </button>
          </div>
        )}
      </div>
    </section>
  )
}
