'use client'

// THE AGENTS' WORLD CUP PICKS — each agent backs one nation to win it and
// argues why (Venice). Then they debate each other's picks. The core mechanic,
// front and centre on the home.

import { useEffect, useState } from 'react'
import { A } from '../lib/arena'
import { PUNDITS } from '../lib/pundits'

type Pick = { role: string; handle: string; country: string; flag: string; reason: string }
type Debate = { handle: string; line: string }

const PUNDIT_LIST = Object.values(PUNDITS)
const colorOf = (handle: string) => PUNDIT_LIST.find((p) => p.handle === handle)?.color ?? A.gold
const avatarOf = (handle: string) => PUNDIT_LIST.find((p) => p.handle === handle)?.avatar ?? '•'

export function WinnerPicks() {
  const [picks, setPicks] = useState<Pick[]>([])
  const [debate, setDebate] = useState<Debate[]>([])
  const [state, setState] = useState<'idle' | 'loading' | 'error'>('idle')

  useEffect(() => {
    fetch('/api/winner-picks').then((r) => r.json()).then((d) => {
      if (d.picks?.length) { setPicks(d.picks); setDebate(d.debate ?? []) }
    }).catch(() => {})
  }, [])

  async function generate() {
    setState('loading')
    try {
      const r = await fetch('/api/winner-picks', { method: 'POST' })
      const d = await r.json()
      if (d.picks?.length) { setPicks(d.picks); setDebate(d.debate ?? []); setState('idle') }
      else setState('error')
    } catch { setState('error') }
  }

  return (
    <section style={{ padding: '56px 0 0' }}>
      <div style={{ marginBottom: 24 }}>
        <div className="mono" style={{ fontSize: 10.5, letterSpacing: 2.4, color: A.gold, marginBottom: 8 }}>THE AGENTS’ WORLD CUP PICKS</div>
        <h2 style={{ fontFamily: A.display, fontWeight: 600, fontSize: 'clamp(26px, 2.6vw, 34px)', letterSpacing: -0.8, color: A.cream, margin: 0 }}>
          Five agents back a winner — and they don’t agree
        </h2>
        <p style={{ fontSize: 14.5, color: A.text2, lineHeight: 1.55, margin: '8px 0 0', maxWidth: 600 }}>
          Each agent commits to one nation to lift the trophy and argues it in its own lane. Then they tear into each other’s picks. Every word generated by Venice.
        </p>
      </div>

      {picks.length === 0 ? (
        <div style={{ background: A.panel, border: `1px solid ${A.borderDim}`, borderRadius: A.radius.lg, padding: '40px 24px', textAlign: 'center' }}>
          {state === 'loading' ? (
            <>
              <div className="cf-think" style={{ display: 'inline-flex', gap: 6, marginBottom: 12 }}>
                {[0, 1, 2].map((i) => <span key={i} style={{ width: 7, height: 7, borderRadius: '50%', background: A.gold }} />)}
              </div>
              <div className="mono" style={{ fontSize: 12.5, color: A.text2 }}>The agents are deliberating…</div>
              <div className="mono" style={{ fontSize: 10.5, color: A.text3, marginTop: 4 }}>Venice · 5 picks + a debate · this can take ~60s</div>
            </>
          ) : (
            <>
              <div style={{ fontSize: 14, color: A.text2, marginBottom: 14 }}>
                {state === 'error' ? 'Venice was busy — try again.' : 'Run the agents to see who they back to win the World Cup.'}
              </div>
              <button onClick={generate} style={{
                padding: '11px 20px', borderRadius: A.radius.md, border: 'none', cursor: 'pointer',
                background: `linear-gradient(180deg, ${A.goldBright}, ${A.goldDim})`, color: '#1a1305', fontFamily: A.body, fontWeight: 700, fontSize: 13,
              }}>✦ Run the agents · Venice</button>
            </>
          )}
        </div>
      ) : (
        <>
          {/* the picks */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 14 }}>
            {picks.map((p) => {
              const c = colorOf(p.handle)
              return (
                <div key={p.handle} style={{ background: A.panel, border: `1px solid ${A.borderDim}`, borderTop: `2px solid ${c}`, borderRadius: A.radius.lg, padding: '16px 15px', display: 'flex', flexDirection: 'column' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 9, marginBottom: 12 }}>
                    <span style={{ width: 28, height: 28, borderRadius: '50%', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', background: c + '1f', border: `1.5px solid ${c}`, color: c, fontFamily: A.mono, fontWeight: 700, fontSize: 12, flexShrink: 0 }}>{avatarOf(p.handle)}</span>
                    <span style={{ fontWeight: 700, fontSize: 12.5, color: A.cream, letterSpacing: 0.3 }}>{p.handle}</span>
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
                    <span style={{ fontSize: 26, lineHeight: 1 }}>{p.flag}</span>
                    <span style={{ fontFamily: A.display, fontSize: 18, fontWeight: 600, color: A.gold, letterSpacing: -0.3 }}>{p.country}</span>
                  </div>
                  <div style={{ fontSize: 12, color: A.text2, lineHeight: 1.5, fontStyle: 'italic' }}>“{p.reason}”</div>
                </div>
              )
            })}
          </div>

          {/* the debate */}
          {debate.length > 0 && (
            <div style={{ marginTop: 18, background: A.panel, border: `1px solid ${A.borderDim}`, borderRadius: A.radius.lg, padding: '18px 22px' }}>
              <div className="mono" style={{ fontSize: 10, letterSpacing: 2, color: A.gold, fontWeight: 600, marginBottom: 14 }}>THE DEBATE</div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                {debate.map((d, i) => {
                  const c = colorOf(d.handle)
                  return (
                    <div key={i} style={{ display: 'flex', gap: 11, alignItems: 'baseline' }}>
                      <span style={{ fontFamily: A.mono, fontWeight: 700, fontSize: 11.5, color: c, width: 70, flexShrink: 0, textAlign: 'right' }}>{d.handle}</span>
                      <span style={{ fontSize: 13.5, color: A.text, lineHeight: 1.5 }}>{d.line}</span>
                    </div>
                  )
                })}
              </div>
            </div>
          )}
        </>
      )}
    </section>
  )
}
